Repository AI-Funding/AI_Funding_BE, pull requests merged in 2022-03, with the labels that each got.

#44 Feature/#9로그인유저정보반환
  src/main/java/com/AiFunding/ToBi/controller/AuthController.java
  src/main/java/com/AiFunding/ToBi/dto/auth/TokenDto.java
  src/main/java/com/AiFunding/ToBi/entity/CustomerInformationEntity.java
  src/main/java/com/AiFunding/ToBi/exception/AlreadyExistUser.java
  src/main/java/com/AiFunding/ToBi/mapper/CustomerInformationRepository.java
  src/main/java/com/AiFunding/ToBi/service/oauth/OAuthService.java
Labels: D-2

#49 hotfix[삭제] OAuthService 중복 삭제
  src/main/java/com/AiFunding/ToBi/service/OAuthService.java
Labels: D-0

#48 Feature/#16 ai 현재종목탭구현 [최종]
  src/main/java/com/AiFunding/ToBi/controller/AiPageController.java
  src/main/java/com/AiFunding/ToBi/dto/ai/page/StockDetailResponseDto.java
  src/main/java/com/AiFunding/ToBi/mapper/AccountStockDetailRepository.java
  src/main/java/com/AiFunding/ToBi/mapper/StockPriceByDayRepository.java
  src/main/java/com/AiFunding/ToBi/service/ai/page/AiService.java
Labels: D-3

#52 Feature/#9로그인유저정보반환
  build.gradle
  src/main/java/com/AiFunding/ToBi/controller/AuthController.java
  src/main/java/com/AiFunding/ToBi/dto/auth/SocialLoginType.java
  src/main/java/com/AiFunding/ToBi/dto/auth/SocialLoginTypeConverter.java
  src/main/java/com/AiFunding/ToBi/service/oauth/JwtTokenUtils.java
  src/main/java/com/AiFunding/ToBi/service/oauth/OAuthService.java
  src/main/java/com/AiFunding/ToBi/service/oauth/social/GoogleOauth.java
  src/main/java/com/AiFunding/ToBi/service/oauth/social/KakaoOauth.java
  src/main/java/com/AiFunding/ToBi/service/oauth/social/SocialOauth.java
  src/main/resources/application.properties
Labels: D-2

#53 Featrue/#41 db에시그널저장
  src/main/java/com/AiFunding/ToBi/controller/TradeSignalController.java
  src/main/java/com/AiFunding/ToBi/dto/trade/signal/TradeSignalDetailDto.java
  src/main/java/com/AiFunding/ToBi/entity/TradeSignalEntity.java
  src/main/java/com/AiFunding/ToBi/mapper/TradeSignalRepository.java
  src/main/java/com/AiFunding/ToBi/mapper/TradingDetailRepository.java
  src/test/java/com/AiFunding/ToBi/entity/TradeTest.java
Labels: D-4
