Repository AI-Funding/AI_Funding_BE, pull requests merged in 2022-02, with the labels that each got.

#34 Feature/#16 ai 현재종목탭구현
  src/main/java/com/AiFunding/ToBi/config/WebSecurityConfig.java
  src/main/java/com/AiFunding/ToBi/controller/AiPageController.java
  src/main/java/com/AiFunding/ToBi/dto/Tab/History/HistoryListResponseDto.java
  src/main/java/com/AiFunding/ToBi/dto/ai/page/AccountInfoResponseDto.java
  src/main/java/com/AiFunding/ToBi/dto/ai/page/CurrStockItemsResponseDto.java
  src/main/java/com/AiFunding/ToBi/dto/ai/page/StockDetailResponseDto.java
  src/main/java/com/AiFunding/ToBi/dto/ai/page/StockInfoResponseDto.java
  src/main/resources/application.properties
Labels: D-0

#39 [수정] comparator 람다식으로 변경
  src/main/java/com/AiFunding/ToBi/service/comparator/AccountComparator.java
  src/main/java/com/AiFunding/ToBi/service/comparator/StockComparator.java
  src/main/java/com/AiFunding/ToBi/service/home/HomeService.java
Labels: D-4

#42 feature / [추가] trade Signal 관련 DTO 추가
  src/main/java/com/AiFunding/ToBi/dto/trade/signal/TradeSignalDetailDto.java
  src/main/java/com/AiFunding/ToBi/dto/trade/signal/TradeSignalRequestDto.java
Labels: D-2

#43 feature/인가코드와 AccessCode 받기 기능 구현
  .gitignore
  build.gradle
  src/main/java/com/AiFunding/ToBi/config/WebSecurityConfig.java
  src/main/java/com/AiFunding/ToBi/controller/AuthController.java
  src/main/java/com/AiFunding/ToBi/entity/CustomerInformationEntity.java
  src/main/java/com/AiFunding/ToBi/service/OAuthService.java
  src/main/resources/application.properties
  src/main/resources/static/index.html
Labels: D-4
